# An `rv.lock` (version 2) style document, from
# https://github.com/extendr/tomledit/issues/5
lockfile <- '# This file is automatically @generated by rv.
version = 2
r_version = "4.4"

[[packages]]
name = "DT"
version = "0.33"
source = { repository = "https://example.com/rpkgs/2025-04-26" }
force_source = false
dependencies = [
    { name = "htmltools", requirement = "(>= 0.3.6)" },
    "httpuv",
    { name = "jsonlite", requirement = "(>= 0.9.16)" },
    "magrittr",
]

[[packages]]
name = "Matrix"
version = "1.7-1"
source = { builtin = true }
force_source = false
dependencies = [
    "lattice",
    "grid",
]
'

test_that("arrays containing inline tables are read as lists", {
  pkgs <- get_item(parse_toml(lockfile), "packages")

  expect_length(pkgs, 2)
  expect_equal(pkgs[[1]]$name, "DT")
  expect_equal(pkgs[[1]]$source, list(repository = "https://example.com/rpkgs/2025-04-26"))

  deps <- pkgs[[1]]$dependencies
  expect_length(deps, 4)
  expect_equal(deps[[1]], list(name = "htmltools", requirement = "(>= 0.3.6)"))
  expect_equal(deps[[2]], "httpuv")
})

test_that("unnamed lists are written as arrays", {
  expect_equal(
    to_toml(as_toml(list(x = list(1, 2, 3)))),
    "x = [1.0, 2.0, 3.0]\n"
  )

  expect_equal(
    to_toml(as_toml(list(deps = list("a", list(name = "b", requirement = ">=1"))))),
    "deps = [\"a\", { name = \"b\", requirement = \">=1\" }]\n"
  )

  expect_equal(to_toml(as_toml(list(x = list()))), "x = []\n")
})

test_that("a list of named lists is written as an array of tables", {
  expect_equal(
    to_toml(as_toml(list(x = list(list(a = 1L), list(a = 2L))))),
    "[[x]]\na = 1\n\n[[x]]\na = 2\n"
  )
})

test_that("an array of tables survives a round trip", {
  doc <- parse_toml(lockfile)
  pkgs <- get_item(doc, "packages")

  round_tripped <- insert_items(parse_toml(lockfile), packages = pkgs)
  expect_equal(
    get_item(parse_toml(to_toml(round_tripped)), "packages"),
    pkgs
  )

  # the rest of the document is left alone
  expect_equal(get_item(round_tripped, "version"), 2L)
  expect_true(any(grepl("@generated by rv", as.character(round_tripped))))
})

test_that("named lists and data.frames are unaffected", {
  expect_equal(
    to_toml(as_toml(list(x = list(a = 1L, b = 2L)))),
    "[x]\na = 1\nb = 2\n"
  )

  df <- data.frame(a = 1:2, b = c("x", "y"))
  expect_equal(
    to_toml(as_toml(list(x = df))),
    "[[x]]\na = 1\nb = \"x\"\n\n[[x]]\na = 2\nb = \"y\"\n"
  )
  expect_equal(
    to_toml(as_toml(list(x = df), df_as_array = FALSE)),
    "[x]\na = [1, 2]\nb = [\"x\", \"y\"]\n"
  )

  expect_error(as_toml(list(x = list(a = 1, 2))))
})
